#!/usr/bin/env node
// Build the publishable font packages.
//
//   fetch pinned upstream → derive charset → subset (harfbuzz) → emit package
//
// Why subset at all: the upstream CJK fonts are 9-17 MB, which is a painful
// download anywhere and an unreliable one from mainland China. The national
// encodings above cover everyday business documents in ~1/7 of the bytes.
//
// Why harfbuzz and not the PDF engine's own subsetter: `buildSubsetFont` in
// pdf-creator deliberately omits `cmap` (a PDF CIDFontType2 selects glyphs by
// CID, so the table is dead weight there). That output is not a usable font
// file — it cannot be re-parsed, and the engine needs `cmap` to map characters
// to glyphs. Distribution subsets must keep it.

import { mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brotliCompressSync } from 'node:zlib';
import subsetFont from 'subset-font';
import { FONTS, GOOGLE_FONTS_SHA, upstreamUrl, charsetFor } from '../fonts.config.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = join(ROOT, '.cache');
const PACKAGES = join(ROOT, 'packages');

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
const mb = (n) => `${(n / 1048576).toFixed(2)} MB`;

async function fetchCached(url, cacheFile) {
  const path = join(CACHE, cacheFile);
  if (existsSync(path)) return readFile(path);

  process.stdout.write(`    downloading ${url.split('/').pop()} … `);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  await mkdir(CACHE, { recursive: true });
  await writeFile(path, bytes);
  process.stdout.write(`${mb(bytes.length)}\n`);
  return bytes;
}

const INDEX_JS = (font) => `// Generated by scripts/build.mjs — do not edit.
//
// The font bytes live in ./data.js and are pulled in with a dynamic import, so
// bundlers split them into their own chunk: an app that never exports a PDF
// never downloads ${font.family}.

let cached = null;

function decodeBase64(base64) {
  if (typeof atob === 'function') {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
    return bytes;
  }
  // Node / SSR — no atob before v16, and Buffer is faster anyway.
  return new Uint8Array(Buffer.from(base64, 'base64'));
}

/**
 * Resolve the embedded ${font.family} subset to TrueType bytes.
 *
 * Pass it straight to ReoGrid's font registry:
 *
 *     import { registerPdfFont, preloadPdfFont } from '@reogrid/pro';
 *     import { ${font.export} } from '${font.pkg}';
 *
 *     registerPdfFont('${font.tag}', ${font.export});
 *     await preloadPdfFont('${font.tag}');
 *
 * @returns {Promise<Uint8Array>}
 */
export async function ${font.export}() {
  if (cached) return cached;
  const { default: base64 } = await import('./data.js');
  cached = decodeBase64(base64);
  return cached;
}

export default ${font.export};
`;

const INDEX_DTS = (font) => `// Generated by scripts/build.mjs — do not edit.

/** Resolve the embedded ${font.family} subset to TrueType (glyf) bytes. */
export declare function ${font.export}(): Promise<Uint8Array>;
export default ${font.export};
`;

const README = (font, stats) => `# ${font.pkg}

A subset of **${font.family}** packaged for [ReoGrid](https://web.reogrid.net)
PDF export, so a browser never has to fetch a ${mb(stats.upstream)} font from a CDN.

\`\`\`bash
npm install ${font.pkg}
\`\`\`

\`\`\`ts
import { registerPdfFont, preloadPdfFont } from '@reogrid/pro';
import { ${font.export} } from '${font.pkg}';

registerPdfFont('${font.tag}', ${font.export});   // wire it up
await preloadPdfFont('${font.tag}');              // once, at app start

grid.saveAsPdf({ font: '${font.tag}', filename: 'report.pdf' });
\`\`\`

The bytes sit behind a dynamic import, so bundlers keep them in their own chunk:
an app that never exports a PDF never downloads them.

## What is in it

| | |
|---|---|
| Upstream | \`${font.upstream.dir}\` @ [\`${GOOGLE_FONTS_SHA.slice(0, 10)}\`](https://github.com/google/fonts/tree/${GOOGLE_FONTS_SHA}/ofl/${font.upstream.dir}) |
| Characters | ${stats.chars.toLocaleString()} (${font.charset.encoding.toUpperCase()} repertoire + ASCII) |
| Upstream size | ${mb(stats.upstream)} |
| Subset | ${kb(stats.subset)} |
| Over the wire | ~${kb(stats.wire)} (base64, brotli) |

Characters outside that repertoire fall back to \`.notdef\` — pass your own font
bytes to \`registerPdfFont\` if you need wider coverage.

## Licence

${font.family} is licensed under the [SIL Open Font License 1.1](./OFL.txt),
which is included in this package and applies to the subset as well. The build
scripts are MIT.
`;

async function buildOne(font) {
  console.log(`\n▸ ${font.pkg}`);

  const source = await fetchCached(
    upstreamUrl(font.upstream.dir, font.upstream.file),
    `${font.upstream.dir}.ttf`,
  );
  const ofl = await fetchCached(
    `https://raw.githubusercontent.com/google/fonts/${GOOGLE_FONTS_SHA}/ofl/${font.upstream.dir}/OFL.txt`,
    `${font.upstream.dir}-OFL.txt`,
  );

  const text = charsetFor(font.charset);
  const subset = await subsetFont(source, text, { targetFormat: 'truetype' });
  const base64 = Buffer.from(subset).toString('base64');
  const wire = brotliCompressSync(Buffer.from(base64)).length;

  const stats = { upstream: source.length, subset: subset.length, wire, chars: [...text].length };
  const dir = join(PACKAGES, font.dir);
  await mkdir(dir, { recursive: true });

  await Promise.all([
    writeFile(join(dir, 'data.js'), `// Generated — ${font.family} subset.\nexport default '${base64}';\n`),
    writeFile(join(dir, 'index.js'), INDEX_JS(font)),
    writeFile(join(dir, 'index.d.ts'), INDEX_DTS(font)),
    writeFile(join(dir, 'README.md'), README(font, stats)),
    writeFile(join(dir, 'OFL.txt'), ofl),
    writeFile(
      join(dir, 'package.json'),
      `${JSON.stringify(
        {
          name: font.pkg,
          version: '1.0.0',
          description: `${font.family} subset for ReoGrid PDF export (${font.tag}).`,
          type: 'module',
          main: './index.js',
          module: './index.js',
          types: './index.d.ts',
          exports: { '.': { types: './index.d.ts', import: './index.js' } },
          files: ['index.js', 'index.d.ts', 'data.js', 'OFL.txt', 'README.md'],
          sideEffects: false,
          keywords: ['reogrid', 'pdf', 'font', 'subset', font.tag],
          license: 'OFL-1.1',
          repository: { type: 'git', url: 'https://github.com/unvell/reogrid-fonts.git', directory: `packages/${font.dir}` },
          homepage: 'https://web.reogrid.net/docs/pdf-export',
        },
        null,
        2,
      )}\n`,
    ),
  ]);

  console.log(
    `    ${stats.chars.toLocaleString()} chars   ` +
      `${mb(stats.upstream)} → ${kb(stats.subset)}   ` +
      `wire ~${kb(wire)}   (1/${Math.round(stats.upstream / wire)})`,
  );
  return { font, stats };
}

async function main() {
  const only = process.argv.slice(2).filter((a) => !a.startsWith('-'));
  const targets = only.length ? FONTS.filter((f) => only.includes(f.tag) || only.includes(f.dir)) : FONTS;
  if (!targets.length) {
    console.error(`No font matched ${only.join(', ')}. Known: ${FONTS.map((f) => f.tag).join(', ')}`);
    process.exit(1);
  }

  if (process.argv.includes('--clean')) await rm(PACKAGES, { recursive: true, force: true });
  console.log(`google/fonts @ ${GOOGLE_FONTS_SHA.slice(0, 10)}`);

  const built = [];
  for (const font of targets) built.push(await buildOne(font));

  const wire = built.reduce((n, b) => n + b.stats.wire, 0);
  const upstream = built.reduce((n, b) => n + b.stats.upstream, 0);
  console.log(`\n${built.length} package(s): ${mb(upstream)} upstream → ~${kb(wire)} over the wire.`);
}

main().catch((error) => {
  console.error(`\nbuild failed: ${error.message}`);
  process.exit(1);
});
