#!/usr/bin/env node
// Build the publishable font packages.
//
//   fetch pinned upstream → derive charset → instance + subset (harfbuzz)
//     → rename → one .ttf per weight → emit package
//
// Why subset at all: the upstream CJK fonts are 9-17 MB, which is a painful
// download anywhere and an unreliable one from mainland China. The national
// encodings above cover everyday business documents in ~1/7 of the bytes.
//
// Why harfbuzz and not the PDF engine's own subsetter: `buildSubsetFont` in
// pdf-creator deliberately omits `cmap` (a PDF CIDFontType2 selects glyphs by
// CID, so the table is dead weight there). That output is not a usable font
// file — it cannot be re-parsed, and the engine needs `cmap` to map characters
// to glyphs. Distribution subsets must keep it.
//
// Why a raw `.ttf` per weight rather than the base64 `data.js` this build used
// to emit: the file is the artifact both consumers want. A bundler resolves it
// through `new URL('./…ttf', import.meta.url)` and keeps it out of the JS
// chunk, and jsDelivr serves the very same file straight from the published
// package — which is what lets ReoGrid's built-in `locale` fonts work with no
// install at all. Base64 was 33% larger and only ever served the first case.

import { mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';
import {
  FONTS,
  GOOGLE_FONTS_SHA,
  WEIGHTS,
  DEFAULT_WEIGHT,
  upstreamUrl,
  charsetFor,
} from '../fonts.config.mjs';
import { renameFont } from './nameTable.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = join(ROOT, '.cache');
const PACKAGES = join(ROOT, 'packages');

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
const mb = (n) => `${(n / 1048576).toFixed(2)} MB`;

/** Version stamped into every generated package.json. Bump to republish. */
const PKG_VERSION = '2.0.0';

/** The `@reogrid/pro` release that understands the per-weight form. */
const MIN_REOGRID = '1.6.0';

/** The weight a bare `loadNotoSansXX()` resolves to. */
const DEFAULT = WEIGHTS.find((w) => w.key === DEFAULT_WEIGHT);

/** `Noto Sans JP` → `NotoSansJP`, the stem every emitted file is named from. */
const stem = (family) => family.replace(/\s+/g, '');

/** Filename of one weight's font file inside the package. */
const fontFile = (font, weight) => `${stem(font.family)}-${weight.style}.ttf`;

/** `loadNotoSansJP` → `notoSansJP`, the name of the all-weights export. */
const varName = (font) => {
  const bare = font.export.replace(/^load/, '');
  return bare.charAt(0).toLowerCase() + bare.slice(1);
};

/** `loadNotoSansJP` + Bold → `loadNotoSansJPBold`; the default face gets `Regular`. */
const loaderName = (font, weight) => `${font.export}${weight.style}`;

async function fetchCached(url, cacheFile) {
  const path = join(CACHE, cacheFile);
  if (existsSync(path)) return readFile(path);

  process.stdout.write(`    downloading ${url.split('/').pop()} … `);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  await mkdir(CACHE, { recursive: true });
  await writeFile(path, bytes);
  process.stdout.write(`${mb(bytes.length)}\n`);
  return bytes;
}

const INDEX_JS = (font) => `// Generated by scripts/build.mjs — do not edit.
//
// ${font.family}, instanced at ${WEIGHTS.map((w) => w.style).join(' / ')} and subset to the
// ${font.charset.encoding.toUpperCase()} repertoire. Each weight is a separate .ttf sitting next to this
// file and resolved through \`import.meta.url\`: a bundler emits it as an asset
// and keeps it out of the JS chunk, so an app that never prints never
// downloads a font.

const CDN = 'https://cdn.jsdelivr.net/npm/${font.pkg}@${PKG_VERSION}';

/** Font file name per weight — also the path to append to the CDN base. */
export const FILES = {
${WEIGHTS.map((w) => `  ${w.key}: '${fontFile(font, w)}',`).join('\n')}
};

const cache = new Map();

/**
 * Where a weight's file lives, as a URL relative to this module.
 *
 * The \`new URL(<string literal>, import.meta.url)\` calls are spelled out one
 * per weight on purpose — that exact shape is what bundlers statically
 * recognise. A computed specifier would silently fall through to a runtime URL
 * that resolves to nothing.
 */
function assetUrl(weight) {
${WEIGHTS.map((w) => `  if (weight === '${w.key}') return new URL('./${fontFile(font, w)}', import.meta.url);`).join('\n')}
  return undefined;
}

async function readAsset(url) {
  if (url.protocol === 'file:') {
    // Node: \`fetch\` does not do file: URLs.
    const { readFile } = await import('node:fs/promises');
    return new Uint8Array(await readFile(url));
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
  return new Uint8Array(await res.arrayBuffer());
}

async function load(weight) {
  const cached = cache.get(weight);
  if (cached) return cached;

  const file = FILES[weight];
  if (!file) {
    throw new Error(
      \`${font.pkg}: unknown weight '\` + weight + \`' — expected \` + Object.keys(FILES).join(', ') + '.',
    );
  }

  let bytes;
  const local = assetUrl(weight);
  try {
    bytes = await readAsset(local);
  } catch (localError) {
    // A bundler that does not understand \`import.meta.url\` assets leaves the
    // file out of its output, and the URL above resolves to a 404. Falling
    // back to the published copy keeps the package working there instead of
    // failing at the moment someone tries to print.
    try {
      bytes = await readAsset(new URL(CDN + '/' + file));
    } catch {
      throw new Error(
        \`${font.pkg}: could not load \` + file + '. Tried ' + local + ' (' + localError.message +
          ') and ' + CDN + '/' + file + '. If your bundler does not emit assets referenced ' +
          'through import.meta.url, fetch the file yourself and pass the bytes to registerPdfFont.',
      );
    }
  }

  cache.set(weight, bytes);
  return bytes;
}

${WEIGHTS.map(
  (w) => `/** ${font.family} ${w.style} (wght ${w.wght}) as TrueType (glyf) bytes. */
export function ${loaderName(font, w)}() {
  return load('${w.key}');
}`,
).join('\n\n')}

/**
 * Every weight, keyed the way ReoGrid's font registry expects. Hand it over
 * whole and \`{ locale: '${font.tag}' }\` picks the right face per cell:
 *
 *     import { registerPdfFont, preloadPdfFont } from '@reogrid/pro';
 *     import { ${varName(font)} } from '${font.pkg}';
 *
 *     registerPdfFont('${font.tag}', ${varName(font)});
 *     await preloadPdfFont('${font.tag}');
 */
export const ${varName(font)} = {
${WEIGHTS.map((w) => `  ${w.key}: ${loaderName(font, w)},`).join('\n')}
};

/**
 * ${font.family} at \`weight\` (default \`'${DEFAULT_WEIGHT}'\`).
 *
 * Called with no argument this matches the pre-2.0 signature, so
 * \`registerPdfFont('${font.tag}', ${font.export})\` keeps working — it just
 * registers the ${DEFAULT.style} face alone, and bold cells fall back to a
 * stroked approximation. Pass \`${varName(font)}\` instead for real bold.
 */
export function ${font.export}(weight = '${DEFAULT_WEIGHT}') {
  return load(weight);
}

export default ${font.export};
`;

const INDEX_DTS = (font) => `// Generated by scripts/build.mjs — do not edit.

export type FontWeight = ${WEIGHTS.map((w) => `'${w.key}'`).join(' | ')};

/** Font file name per weight, relative to this package's root. */
export declare const FILES: Record<FontWeight, string>;

${WEIGHTS.map(
  (w) => `/** ${font.family} ${w.style} (wght ${w.wght}) as TrueType (glyf) bytes. */
export declare function ${loaderName(font, w)}(): Promise<Uint8Array>;`,
).join('\n\n')}

/** Every weight, in the shape ReoGrid's \`registerPdfFont\` accepts. */
export declare const ${varName(font)}: Record<FontWeight, () => Promise<Uint8Array>>;

/** ${font.family} at \`weight\` (default \`'${DEFAULT_WEIGHT}'\`). */
export declare function ${font.export}(weight?: FontWeight): Promise<Uint8Array>;
export default ${font.export};
`;

const README = (font, stats) => `# ${font.pkg}

**${font.family}** — subset to the ${font.charset.encoding.toUpperCase()} repertoire and instanced at
${WEIGHTS.map((w) => `${w.style} (${w.wght})`).join(', ')} — packaged for
[ReoGrid](https://web.reogrid.net) PDF export, so a browser never has to fetch a
${mb(stats.upstream)} variable font from a CDN.

\`\`\`bash
npm install ${font.pkg}
\`\`\`

\`\`\`ts
import { registerPdfFont, preloadPdfFont } from '@reogrid/pro';
import { ${varName(font)} } from '${font.pkg}';

registerPdfFont('${font.tag}', ${varName(font)});   // all three weights
await preloadPdfFont('${font.tag}');                // once, at app start

grid.saveAsPdf({ locale: '${font.tag}', filename: 'report.pdf' });
\`\`\`

Bold cells print with real Bold outlines instead of a stroked approximation. To
keep the download to a single face, register just that one:

\`\`\`ts
import { ${loaderName(font, DEFAULT)} } from '${font.pkg}';
registerPdfFont('${font.tag}', ${loaderName(font, DEFAULT)});
\`\`\`

> The per-weight form needs **\`@reogrid/pro\` ${MIN_REOGRID} or newer**. Older
> versions accept the single-face form above.

## What is in it

| | |
|---|---|
| Upstream | \`${font.upstream.dir}\` @ [\`${GOOGLE_FONTS_SHA.slice(0, 10)}\`](https://github.com/google/fonts/tree/${GOOGLE_FONTS_SHA}/ofl/${font.upstream.dir}) |
| Characters | ${stats.chars.toLocaleString()} (${font.charset.encoding.toUpperCase()} repertoire + ASCII + \`¥₩€£¢\`) |
| Upstream | ${mb(stats.upstream)} (variable) |
${WEIGHTS.map((w) => `| ${w.style} — \`${fontFile(font, w)}\` | ${kb(stats.weights[w.key])} |`).join('\n')}

Each weight is a plain static face: \`fvar\`/\`gvar\` are gone, \`OS/2.usWeightClass\`
is set, and the \`name\` table says which weight it is. A consumer that embeds
\`glyf\` outlines without applying variations — which is what a PDF engine does —
therefore draws the weight you asked for. (Upstream's variable font defaults to
\`wght\` 100, which is why embedding it directly produces a hairline document.)

Characters outside that repertoire fall back to \`.notdef\` — pass your own font
bytes to \`registerPdfFont\` if you need wider coverage.

## Without a bundler

The \`.ttf\` files are published in the package, so a CDN serves them directly:

\`\`\`
https://cdn.jsdelivr.net/npm/${font.pkg}@${PKG_VERSION}/${fontFile(font, DEFAULT)}
\`\`\`

That is where ReoGrid's built-in \`{ locale: '${font.tag}' }\` font comes from when
you have not registered anything yourself.

## Licence

${font.family} is licensed under the [SIL Open Font License 1.1](./OFL.txt),
which is included in this package and applies to the subset as well. The build
scripts are MIT.
`;

async function buildOne(font) {
  console.log(`\n▸ ${font.pkg}`);

  const source = await fetchCached(
    upstreamUrl(font.upstream.dir, font.upstream.file),
    `${font.upstream.dir}.ttf`,
  );
  const ofl = await fetchCached(
    `https://raw.githubusercontent.com/google/fonts/${GOOGLE_FONTS_SHA}/ofl/${font.upstream.dir}/OFL.txt`,
    `${font.upstream.dir}-OFL.txt`,
  );

  const text = charsetFor(font.charset);
  const dir = join(PACKAGES, font.dir);
  await mkdir(dir, { recursive: true });

  const weights = {};
  for (const weight of WEIGHTS) {
    const subset = await subsetFont(source, text, {
      targetFormat: 'truetype',
      variationAxes: { wght: weight.wght },
    });
    // harfbuzz updates `OS/2.usWeightClass` when it instances but leaves `name`
    // alone, so without this every face would still call itself Thin — and a
    // PDF's /BaseFont with it. See scripts/nameTable.mjs.
    const named = renameFont(subset, { family: font.family, style: weight.style });
    await writeFile(join(dir, fontFile(font, weight)), named);
    weights[weight.key] = named.length;
    console.log(
      `    ${weight.style.padEnd(8)} wght ${String(weight.wght).padStart(3)}   ` +
        `${kb(named.length).padStart(8)}   ${fontFile(font, weight)}`,
    );
  }

  const stats = { upstream: source.length, weights, chars: [...text].length };

  // Files the old base64 build left behind; a stale `data.js` next to the new
  // `.ttf`s would be published and would still be Thin.
  await Promise.all(
    ['data.js', 'data-thin.js', 'data-normal.js', 'data-bold.js'].map((f) =>
      rm(join(dir, f), { force: true }),
    ),
  );

  await Promise.all([
    writeFile(join(dir, 'index.js'), INDEX_JS(font)),
    writeFile(join(dir, 'index.d.ts'), INDEX_DTS(font)),
    writeFile(join(dir, 'README.md'), README(font, stats)),
    writeFile(join(dir, 'OFL.txt'), ofl),
    writeFile(
      join(dir, 'package.json'),
      `${JSON.stringify(
        {
          name: font.pkg,
          version: PKG_VERSION,
          description:
            `${font.family} subset (${WEIGHTS.map((w) => w.style).join('/')}) ` +
            `for ReoGrid PDF export (${font.tag}).`,
          type: 'module',
          main: './index.js',
          module: './index.js',
          types: './index.d.ts',
          exports: {
            '.': { types: './index.d.ts', import: './index.js' },
            './package.json': './package.json',
            './*.ttf': './*.ttf',
          },
          files: [
            'index.js',
            'index.d.ts',
            ...WEIGHTS.map((w) => fontFile(font, w)),
            'OFL.txt',
            'README.md',
          ],
          sideEffects: false,
          keywords: ['reogrid', 'pdf', 'font', 'subset', font.tag],
          license: 'OFL-1.1',
          repository: {
            type: 'git',
            url: 'https://github.com/unvell/reogrid-fonts.git',
            directory: `packages/${font.dir}`,
          },
          homepage: 'https://web.reogrid.net/docs/pdf-export',
        },
        null,
        2,
      )}\n`,
    ),
  ]);

  const total = Object.values(weights).reduce((n, v) => n + v, 0);
  console.log(
    `    ${stats.chars.toLocaleString()} chars   ` +
      `${mb(stats.upstream)} → ${mb(total)} across ${WEIGHTS.length} weights`,
  );
  return { font, stats, total };
}

async function main() {
  const only = process.argv.slice(2).filter((a) => !a.startsWith('-'));
  const targets = only.length
    ? FONTS.filter((f) => only.includes(f.tag) || only.includes(f.dir))
    : FONTS;
  if (!targets.length) {
    console.error(
      `No font matched ${only.join(', ')}. Known: ${FONTS.map((f) => f.tag).join(', ')}`,
    );
    process.exit(1);
  }

  if (process.argv.includes('--clean')) await rm(PACKAGES, { recursive: true, force: true });
  console.log(
    `google/fonts @ ${GOOGLE_FONTS_SHA.slice(0, 10)}   ` +
      `weights: ${WEIGHTS.map((w) => `${w.key}=${w.wght}`).join(' ')}`,
  );

  const built = [];
  for (const font of targets) built.push(await buildOne(font));

  const total = built.reduce((n, b) => n + b.total, 0);
  const upstream = built.reduce((n, b) => n + b.stats.upstream, 0);
  console.log(`\n${built.length} package(s): ${mb(upstream)} upstream → ${mb(total)} published.`);
}

main().catch((error) => {
  console.error(`\nbuild failed: ${error.message}`);
  process.exit(1);
});
